CREATE TABLE TABLE_DATA_1
(
no number(10),
create_date DATE
);

CREATE TABLE TABLE_DATA_2
(
no number(10),
create_date DATE
);

CREATE TABLE TABLE_COLC
(
std_date DATE,
CHECK_DATA1 VARCHAR2(6),
CHECK_DATA2 VARCHAR2(6)
);

--테이블 1,2 데이터
INSERT INTO TABLE_DATA_1 VALUES (1, '2023-04-01');
INSERT INTO TABLE_DATA_1 VALUES (2, '2023-04-02');
INSERT INTO TABLE_DATA_1 VALUES (3, '2023-04-03');
INSERT INTO TABLE_DATA_1 VALUES (4, '2023-04-04');

select * from TABLE_DATA_1;

INSERT INTO TABLE_DATA_2 VALUES (1, '2023-04-02');
INSERT INTO TABLE_DATA_2 VALUES (2, '2023-04-03');
INSERT INTO TABLE_DATA_2 VALUES (3, '2023-04-04');
INSERT INTO TABLE_DATA_2 VALUES (4, '2023-04-05');

select * from TABLE_DATA_2;

--COLC 병합
select * from TABLE_COLC;
--DELETE from TABLE_COLC;

MERGE INTO TABLE_COLC CL
USING TABLE_DATA_1 T1 
ON (CL.STD_DATE = T1.CREATE_DATE) -- 조건추가
WHEN MATCHED THEN 
    UPDATE SET CHECK_DATA1 = 'Y'
    --DELETE WHERE 
WHEN NOT MATCHED THEN 
    INSERT VALUES (T1.CREATE_DATE,'Y', 'N');
    
MERGE INTO TABLE_COLC CL
USING TABLE_DATA_2 T2 
ON (CL.STD_DATE = T2.CREATE_DATE) -- 조건추가
WHEN MATCHED THEN 
    UPDATE SET CHECK_DATA2 = 'Y'
    --DELETE WHERE 
WHEN NOT MATCHED THEN 
    INSERT VALUES (T2.CREATE_DATE,'N','Y');