CREATE TABLE ONLINE_SALE (
ONLINE_SALE_ID NUMBER NOT NULL,
USER_ID NUMBER NOT NULL,
PRODUCT_ID NUMBER NOT NULL,
SALES_AMOUNT NUMBER NOT NULL,
SALES_DATE DATE NOT NULL
);


INSERT INTO ONLINE_SALE (ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE)
VALUES (1, 1, 3, 2, TO_DATE('2022-02-25', 'YYYY-MM-DD'));

INSERT INTO ONLINE_SALE (ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE)
VALUES (2, 1, 4, 1, TO_DATE('2022-03-01', 'YYYY-MM-DD'));

INSERT INTO ONLINE_SALE (ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE)
VALUES (4, 2, 4, 2, TO_DATE('2022-03-12', 'YYYY-MM-DD'));

INSERT INTO ONLINE_SALE (ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE)
VALUES (3, 1, 3, 3, TO_DATE('2022-03-31', 'YYYY-MM-DD'));

INSERT INTO ONLINE_SALE (ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE)
VALUES (5, 3, 5, 1, TO_DATE('2022-04-03', 'YYYY-MM-DD'));

INSERT INTO ONLINE_SALE (ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE)
VALUES (6, 2, 4, 1, TO_DATE('2022-04-06', 'YYYY-MM-DD'));

INSERT INTO ONLINE_SALE (ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE)
VALUES (2, 1, 4, 2, TO_DATE('2022-05-11', 'YYYY-MM-DD'));

select *
from ONLINE_SALE;

select user_id ,product_id
from ONLINE_SALE
group by user_id, product_id
HAVING count(user_id) > 1
order by user_id, product_id desc;



